import type { Property, Category } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Apartments",
    slug: "apartments",
    description: "Modern apartments in prime locations",
    icon: "🏢",
    order: 1,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "2",
    name: "Villas",
    slug: "villas",
    description: "Luxury villas with premium amenities",
    icon: "🏡",
    order: 2,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "3",
    name: "Townhouses",
    slug: "townhouses",
    description: "Spacious townhouses for families",
    icon: "🏘️",
    order: 3,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "4",
    name: "Commercial",
    slug: "commercial",
    description: "Commercial properties for business",
    icon: "🏢",
    order: 4,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
]

export const properties: Property[] = [
  {
    id: "1",
    title: "Luxury Apartment in New Cairo with Pool View",
    description:
      "Stunning 3-bedroom apartment in the heart of New Cairo featuring modern amenities, pool view, and premium finishes. Located in a gated community with 24/7 security, gym, and shopping center nearby.",
    price: 3500000,
    pricePerMeter: 25000,
    location: "Fifth Settlement",
    area: "New Cairo",
    bedrooms: 3,
    bathrooms: 2,
    size: 140,
    floor: 5,
    totalFloors: 12,
    yearBuilt: 2022,
    categoryId: "1",
    propertyType: "sale",
    images: [
      {
        id: "1",
        url: "/images/property-1.jpg",
        alt: "Modern apartment exterior",
        order: 1,
        isMain: true,
      },
      {
        id: "2",
        url: "/images/property-2.jpg",
        alt: "Apartment living room",
        order: 2,
        isMain: false,
      },
      {
        id: "3",
        url: "/images/property-3.jpg",
        alt: "Modern kitchen",
        order: 3,
        isMain: false,
      },
      {
        id: "4",
        url: "/images/property-4.jpg",
        alt: "Master bedroom",
        order: 4,
        isMain: false,
      },
    ],
    features: ["Swimming Pool", "Gym", "Security", "Parking", "Garden"],
    amenities: ["Swimming Pool", "Gym", "Security", "Parking", "Garden", "Central AC"],
    ownerType: "owner",
    isNew: true,
    isFeatured: true,
    isVerified: true,
    views: 1250,
    contactInfo: {
      name: "Ahmed Hassan",
      phone: "+20 100 123 4567",
      whatsapp: "+20 100 123 4567",
      email: "ahmed@example.com",
      isVerified: true,
      responseTime: "1 hour",
    },
    location_coords: {
      lat: 30.0444,
      lng: 31.2357,
    },
    ratings: {
      schools: 8.5,
      transportation: 7.2,
      shopping: 9.0,
      restaurants: 8.8,
      safety: 9.2,
      quietness: 6.5,
    },
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    title: "Spacious Villa in Sheikh Zayed with Private Garden",
    description:
      "Beautiful 5-bedroom villa in Sheikh Zayed featuring a private garden, swimming pool, and modern design. Perfect for families looking for luxury and comfort in a quiet neighborhood.",
    price: 8500000,
    pricePerMeter: 30000,
    location: "Beverly Hills",
    area: "Sheikh Zayed",
    bedrooms: 5,
    bathrooms: 4,
    size: 280,
    floor: 0,
    totalFloors: 2,
    yearBuilt: 2021,
    categoryId: "2",
    propertyType: "sale",
    images: [
      {
        id: "5",
        url: "/images/villa-1.jpg",
        alt: "Luxury villa exterior",
        order: 1,
        isMain: true,
      },
      {
        id: "6",
        url: "/images/villa-2.jpg",
        alt: "Villa garden view",
        order: 2,
        isMain: false,
      },
    ],
    features: ["Private Garden", "Swimming Pool", "Garage", "Maid's Room", "Roof Terrace"],
    amenities: ["Swimming Pool", "Garden", "Parking", "Security", "Central AC"],
    ownerType: "owner",
    isNew: false,
    isFeatured: true,
    isVerified: true,
    views: 890,
    contactInfo: {
      name: "Sara Mohamed",
      phone: "+20 101 234 5678",
      whatsapp: "+20 101 234 5678",
      email: "sara@example.com",
      isVerified: true,
      responseTime: "30 minutes",
    },
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
  },
  {
    id: "3",
    title: "Modern Studio for Rent in Maadi",
    description:
      "Fully furnished studio apartment in Maadi, perfect for young professionals. Features modern appliances, high-speed internet, and close to metro station.",
    price: 8000,
    pricePerMeter: 160,
    location: "Maadi Degla",
    area: "Maadi",
    bedrooms: 0,
    bathrooms: 1,
    size: 50,
    floor: 3,
    totalFloors: 8,
    yearBuilt: 2020,
    categoryId: "1",
    propertyType: "rent",
    images: [
      {
        id: "7",
        url: "/images/property-5.jpg",
        alt: "Modern studio",
        order: 1,
        isMain: true,
      },
    ],
    features: ["Furnished", "High-Speed Internet", "Near Metro", "Balcony"],
    amenities: ["Furnished", "Wifi", "Elevator", "Security"],
    ownerType: "broker",
    isNew: true,
    isFeatured: false,
    isVerified: true,
    views: 456,
    contactInfo: {
      name: "Mohamed Ali",
      phone: "+20 102 345 6789",
      whatsapp: "+20 102 345 6789",
      email: "mohamed@example.com",
      isVerified: false,
      responseTime: "2 hours",
    },
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
  },
  {
    id: "4",
    title: "Commercial Office Space in Downtown Cairo",
    description:
      "Prime commercial office space in downtown Cairo, perfect for businesses. Features modern amenities, parking spaces, and excellent accessibility to public transportation.",
    price: 2500000,
    pricePerMeter: 20000,
    location: "Downtown",
    area: "Cairo",
    bedrooms: 0,
    bathrooms: 2,
    size: 125,
    floor: 8,
    totalFloors: 15,
    yearBuilt: 2019,
    categoryId: "4",
    propertyType: "sale",
    images: [
      {
        id: "8",
        url: "/images/commercial-1.jpg",
        alt: "Modern office space",
        order: 1,
        isMain: true,
      },
    ],
    features: ["Conference Rooms", "Parking", "High-Speed Internet", "Reception Area"],
    amenities: ["Parking", "Wifi", "Elevator", "Security", "Central AC"],
    ownerType: "broker",
    isNew: false,
    isFeatured: true,
    isVerified: true,
    views: 678,
    contactInfo: {
      name: "Amr Khaled",
      phone: "+20 103 456 7890",
      whatsapp: "+20 103 456 7890",
      email: "amr@example.com",
      isVerified: true,
      responseTime: "1 hour",
    },
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
  },
  {
    id: "5",
    title: "Penthouse with Nile View in Zamalek",
    description:
      "Exclusive penthouse apartment with stunning Nile views in the prestigious Zamalek district. Features luxury finishes, private terrace, and premium location.",
    price: 12000000,
    pricePerMeter: 40000,
    location: "Zamalek",
    area: "Zamalek",
    bedrooms: 4,
    bathrooms: 3,
    size: 300,
    floor: 12,
    totalFloors: 12,
    yearBuilt: 2023,
    categoryId: "1",
    propertyType: "sale",
    images: [
      {
        id: "9",
        url: "/images/property-6.jpg",
        alt: "Penthouse with Nile view",
        order: 1,
        isMain: true,
      },
    ],
    features: ["Nile View", "Private Terrace", "Luxury Finishes", "Concierge Service"],
    amenities: ["Swimming Pool", "Gym", "Security", "Parking", "Central AC"],
    ownerType: "owner",
    isNew: true,
    isFeatured: true,
    isVerified: true,
    views: 2100,
    contactInfo: {
      name: "Nadia Ibrahim",
      phone: "+20 104 567 8901",
      whatsapp: "+20 104 567 8901",
      email: "nadia@example.com",
      isVerified: true,
      responseTime: "15 minutes",
    },
    createdAt: "2024-01-25",
    updatedAt: "2024-01-25",
  },
  {
    id: "6",
    title: "Family Townhouse in 6th of October",
    description:
      "Spacious 4-bedroom townhouse in 6th of October City, perfect for families. Features private garden, garage, and access to community amenities including pool and playground.",
    price: 4200000,
    pricePerMeter: 21000,
    location: "Beverly Hills",
    area: "6th of October",
    bedrooms: 4,
    bathrooms: 3,
    size: 200,
    floor: 0,
    totalFloors: 2,
    yearBuilt: 2021,
    categoryId: "3",
    propertyType: "sale",
    images: [
      {
        id: "10",
        url: "/images/property-1.jpg",
        alt: "Family townhouse",
        order: 1,
        isMain: true,
      },
    ],
    features: ["Private Garden", "Garage", "Community Pool", "Playground", "Security"],
    amenities: ["Swimming Pool", "Garden", "Parking", "Security", "Playground"],
    ownerType: "owner",
    isNew: false,
    isFeatured: false,
    isVerified: true,
    views: 734,
    contactInfo: {
      name: "Omar Hassan",
      phone: "+20 105 678 9012",
      whatsapp: "+20 105 678 9012",
      email: "omar@example.com",
      isVerified: true,
      responseTime: "45 minutes",
    },
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
  },
]
